[project]
name = "resiliencebench"
version = "0.7.0"
description = "ResilienceBench CLI"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
resbench = "scripts.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"