name: docker
on:
  push:
    tags: ['v*.*.*']
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} -f docker/Dockerfile .
      - name: Push
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}